/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
// SWITCH address and mask defines
#pragma	ioport	SWITCH_Data_ADDR:	0x4
BYTE			SWITCH_Data_ADDR;
#pragma	ioport	SWITCH_DriveMode_0_ADDR:	0x104
BYTE			SWITCH_DriveMode_0_ADDR;
#pragma	ioport	SWITCH_DriveMode_1_ADDR:	0x105
BYTE			SWITCH_DriveMode_1_ADDR;
#pragma	ioport	SWITCH_DriveMode_2_ADDR:	0x7
BYTE			SWITCH_DriveMode_2_ADDR;
#pragma	ioport	SWITCH_GlobalSelect_ADDR:	0x6
BYTE			SWITCH_GlobalSelect_ADDR;
#pragma	ioport	SWITCH_IntCtrl_0_ADDR:	0x106
BYTE			SWITCH_IntCtrl_0_ADDR;
#pragma	ioport	SWITCH_IntCtrl_1_ADDR:	0x107
BYTE			SWITCH_IntCtrl_1_ADDR;
#pragma	ioport	SWITCH_IntEn_ADDR:	0x5
BYTE			SWITCH_IntEn_ADDR;
#define SWITCH_MASK 0x10
// LED1 address and mask defines
#pragma	ioport	LED1_Data_ADDR:	0x4
BYTE			LED1_Data_ADDR;
#pragma	ioport	LED1_DriveMode_0_ADDR:	0x104
BYTE			LED1_DriveMode_0_ADDR;
#pragma	ioport	LED1_DriveMode_1_ADDR:	0x105
BYTE			LED1_DriveMode_1_ADDR;
#pragma	ioport	LED1_DriveMode_2_ADDR:	0x7
BYTE			LED1_DriveMode_2_ADDR;
#pragma	ioport	LED1_GlobalSelect_ADDR:	0x6
BYTE			LED1_GlobalSelect_ADDR;
#pragma	ioport	LED1_IntCtrl_0_ADDR:	0x106
BYTE			LED1_IntCtrl_0_ADDR;
#pragma	ioport	LED1_IntCtrl_1_ADDR:	0x107
BYTE			LED1_IntCtrl_1_ADDR;
#pragma	ioport	LED1_IntEn_ADDR:	0x5
BYTE			LED1_IntEn_ADDR;
#define LED1_MASK 0x1
