//*****************************************************************************
//*****************************************************************************
//  FILENAME: TempCounter.h
//   Version: 2.5, Updated on 2015/3/4 at 22:23:43
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Counter16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef TempCounter_INCLUDE
#define TempCounter_INCLUDE

#include <m8c.h>

#pragma fastcall16 TempCounter_EnableInt
#pragma fastcall16 TempCounter_DisableInt
#pragma fastcall16 TempCounter_Start
#pragma fastcall16 TempCounter_Stop
#pragma fastcall16 TempCounter_wReadCounter              // Read  DR0
#pragma fastcall16 TempCounter_WritePeriod               // Write DR1
#pragma fastcall16 TempCounter_wReadCompareValue         // Read  DR2
#pragma fastcall16 TempCounter_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wTempCounter_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wTempCounter_ReadCompareValue         // Read  DR2 (Deprecated)

//-------------------------------------------------
// Prototypes of the TempCounter API.
//-------------------------------------------------
extern void TempCounter_EnableInt(void);                           // Proxy Class 1
extern void TempCounter_DisableInt(void);                          // Proxy Class 1
extern void TempCounter_Start(void);                               // Proxy Class 1
extern void TempCounter_Stop(void);                                // Proxy Class 1
extern WORD TempCounter_wReadCounter(void);                        // Proxy Class 2
extern void TempCounter_WritePeriod(WORD wPeriod);                 // Proxy Class 1
extern WORD TempCounter_wReadCompareValue(void);                   // Proxy Class 1
extern void TempCounter_WriteCompareValue(WORD wCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wTempCounter_ReadCounter(void);            // Deprecated
extern WORD wTempCounter_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for TempCounter API's.
//--------------------------------------------------

#define TempCounter_CONTROL_REG_START_BIT      ( 0x01 )
#define TempCounter_INT_REG_ADDR               ( 0x0e1 )
#define TempCounter_INT_MASK                   ( 0x20 )


//--------------------------------------------------
// Constants for TempCounter user defined values
//--------------------------------------------------

#define TempCounter_PERIOD                     ( 0x7cff )
#define TempCounter_COMPARE_VALUE              ( 0x3e80 )


//-------------------------------------------------
// Register Addresses for TempCounter
//-------------------------------------------------

#pragma ioport  TempCounter_COUNTER_LSB_REG:    0x030      //DR0 Counter register LSB
BYTE            TempCounter_COUNTER_LSB_REG;
#pragma ioport  TempCounter_COUNTER_MSB_REG:    0x034      //DR0 Counter register MSB
BYTE            TempCounter_COUNTER_MSB_REG;
#pragma ioport  TempCounter_PERIOD_LSB_REG: 0x031          //DR1 Period register LSB
BYTE            TempCounter_PERIOD_LSB_REG;
#pragma ioport  TempCounter_PERIOD_MSB_REG: 0x035          //DR1 Period register MSB
BYTE            TempCounter_PERIOD_MSB_REG;
#pragma ioport  TempCounter_COMPARE_LSB_REG:    0x032      //DR2 Compare register LSB
BYTE            TempCounter_COMPARE_LSB_REG;
#pragma ioport  TempCounter_COMPARE_MSB_REG:    0x036      //DR2 Compare register MSB
BYTE            TempCounter_COMPARE_MSB_REG;
#pragma ioport  TempCounter_CONTROL_LSB_REG:    0x033      //Control register LSB
BYTE            TempCounter_CONTROL_LSB_REG;
#pragma ioport  TempCounter_CONTROL_MSB_REG:    0x037      //Control register MSB
BYTE            TempCounter_CONTROL_MSB_REG;
#pragma ioport  TempCounter_FUNC_LSB_REG:   0x130          //Function register LSB
BYTE            TempCounter_FUNC_LSB_REG;
#pragma ioport  TempCounter_FUNC_MSB_REG:   0x134          //Function register MSB
BYTE            TempCounter_FUNC_MSB_REG;
#pragma ioport  TempCounter_INPUT_LSB_REG:  0x131          //Input register LSB
BYTE            TempCounter_INPUT_LSB_REG;
#pragma ioport  TempCounter_INPUT_MSB_REG:  0x135          //Input register MSB
BYTE            TempCounter_INPUT_MSB_REG;
#pragma ioport  TempCounter_OUTPUT_LSB_REG: 0x132          //Output register LSB
BYTE            TempCounter_OUTPUT_LSB_REG;
#pragma ioport  TempCounter_OUTPUT_MSB_REG: 0x136          //Output register MSB
BYTE            TempCounter_OUTPUT_MSB_REG;
#pragma ioport  TempCounter_INT_REG:       0x0e1           //Interrupt Mask Register
BYTE            TempCounter_INT_REG;


//-------------------------------------------------
// TempCounter Macro 'Functions'
//-------------------------------------------------

#define TempCounter_Start_M \
   ( TempCounter_CONTROL_LSB_REG |=  TempCounter_CONTROL_REG_START_BIT )

#define TempCounter_Stop_M  \
   ( TempCounter_CONTROL_LSB_REG &= ~TempCounter_CONTROL_REG_START_BIT )

#define TempCounter_EnableInt_M   \
   M8C_EnableIntMask(  TempCounter_INT_REG, TempCounter_INT_MASK )

#define TempCounter_DisableInt_M  \
   M8C_DisableIntMask( TempCounter_INT_REG, TempCounter_INT_MASK )

#endif
// end of file TempCounter.h
