/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// I2CHWSDA address and mask defines
#pragma	ioport	I2CHWSDA_Data_ADDR:	0x4
BYTE			I2CHWSDA_Data_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSDA_IntEn_ADDR:	0x5
BYTE			I2CHWSDA_IntEn_ADDR;
#define I2CHWSDA_MASK 0x20
// UART_RX_IN address and mask defines
#pragma	ioport	UART_RX_IN_Data_ADDR:	0x4
BYTE			UART_RX_IN_Data_ADDR;
#pragma	ioport	UART_RX_IN_DriveMode_0_ADDR:	0x104
BYTE			UART_RX_IN_DriveMode_0_ADDR;
#pragma	ioport	UART_RX_IN_DriveMode_1_ADDR:	0x105
BYTE			UART_RX_IN_DriveMode_1_ADDR;
#pragma	ioport	UART_RX_IN_DriveMode_2_ADDR:	0x7
BYTE			UART_RX_IN_DriveMode_2_ADDR;
#pragma	ioport	UART_RX_IN_GlobalSelect_ADDR:	0x6
BYTE			UART_RX_IN_GlobalSelect_ADDR;
#pragma	ioport	UART_RX_IN_IntCtrl_0_ADDR:	0x106
BYTE			UART_RX_IN_IntCtrl_0_ADDR;
#pragma	ioport	UART_RX_IN_IntCtrl_1_ADDR:	0x107
BYTE			UART_RX_IN_IntCtrl_1_ADDR;
#pragma	ioport	UART_RX_IN_IntEn_ADDR:	0x5
BYTE			UART_RX_IN_IntEn_ADDR;
#define UART_RX_IN_MASK 0x40
// I2CHWSCL address and mask defines
#pragma	ioport	I2CHWSCL_Data_ADDR:	0x4
BYTE			I2CHWSCL_Data_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSCL_IntEn_ADDR:	0x5
BYTE			I2CHWSCL_IntEn_ADDR;
#define I2CHWSCL_MASK 0x80
// UART_TX_OUT address and mask defines
#pragma	ioport	UART_TX_OUT_Data_ADDR:	0x8
BYTE			UART_TX_OUT_Data_ADDR;
#pragma	ioport	UART_TX_OUT_DriveMode_0_ADDR:	0x108
BYTE			UART_TX_OUT_DriveMode_0_ADDR;
#pragma	ioport	UART_TX_OUT_DriveMode_1_ADDR:	0x109
BYTE			UART_TX_OUT_DriveMode_1_ADDR;
#pragma	ioport	UART_TX_OUT_DriveMode_2_ADDR:	0xb
BYTE			UART_TX_OUT_DriveMode_2_ADDR;
#pragma	ioport	UART_TX_OUT_GlobalSelect_ADDR:	0xa
BYTE			UART_TX_OUT_GlobalSelect_ADDR;
#pragma	ioport	UART_TX_OUT_IntCtrl_0_ADDR:	0x10a
BYTE			UART_TX_OUT_IntCtrl_0_ADDR;
#pragma	ioport	UART_TX_OUT_IntCtrl_1_ADDR:	0x10b
BYTE			UART_TX_OUT_IntCtrl_1_ADDR;
#pragma	ioport	UART_TX_OUT_IntEn_ADDR:	0x9
BYTE			UART_TX_OUT_IntEn_ADDR;
#define UART_TX_OUT_MASK 0x80
